export const MOCK_ANALYSIS = {
    overallScore: 7.8,
    riskLevel: "High",
    completenessScore: 82,
    clauses: [
        {
            id: 1,
            title: "Unilateral Termination Without Cause",
            type: "Termination",
            riskScore: 91,
            riskLevel: "Critical",
            agent: "Risk Scoring",
            negotiable: true,
            confidence: 96,
            original: "The Client may terminate this agreement at any time without prior notice and without liability for any work completed or in progress.",
            plain: "The client can cancel your project ANY time, for ANY reason, without paying you a single rupee for work already done — even if you spent weeks on it.",
            counter: "Either party may terminate this agreement with a minimum of 30 days written notice. Upon termination, the Client shall pay for all work completed up to the date of termination, calculated on a pro-rata basis at the agreed project rate.",
            financialExposure: "₹50,000–₹2,00,000",
        },
        {
            id: 2,
            title: "Immediate IP Assignment on Creation",
            type: "Intellectual Property",
            riskScore: 85,
            riskLevel: "High",
            agent: "Risk Scoring",
            negotiable: true,
            confidence: 94,
            original: "All intellectual property rights in any work produced under this agreement shall vest in the Client immediately upon creation, irrespective of whether payment has been made.",
            plain: "The client owns all your work the second you create it, even if they never pay your invoice.",
            counter: "Intellectual property rights in the final deliverables shall transfer to the Client only upon receipt of full and final payment for the respective deliverables. Until such payment, the Contractor retains all rights.",
            financialExposure: "Full project value",
            regulatoryNote: "May conflict with Sec 19 of Copyright Act 1957 without valid consideration.",
        },
        {
            id: 3,
            title: "2-Year Broad Non-Compete",
            type: "Restrictive Covenants",
            riskScore: 88,
            riskLevel: "High",
            agent: "Regulatory",
            negotiable: true,
            confidence: 98,
            original: "The Contractor agrees not to engage in any similar business or provide services to any competitor of the Client globally for a period of two (2) years following termination.",
            plain: "You are banned from doing similar work for ANY other company, ANYWHERE in the world, for 2 years after this project ends.",
            counter: "The Contractor agrees not to actively solicit the current, active clients of the Client for a period of six (6) months following the termination of this agreement. This shall not restrict the Contractor’s general right to practice their profession.",
            regulatoryNote: "Void under Section 27, Indian Contract Act 1872 (Restraint of Trade).",
        },
        {
            id: 4,
            title: "Uncapped Indemnification",
            type: "Liability",
            riskScore: 78,
            riskLevel: "High",
            agent: "Consistency",
            negotiable: true,
            confidence: 91,
            original: "The Contractor shall indemnify and hold the Client harmless against ALL claims, losses, and damages arising from this agreement.",
            plain: "If the client gets sued over something related to your work, YOU have to pay all their legal fees and damages, with absolutely no limit.",
            counter: "The Contractor's total liability under this agreement, including indemnification, shall not exceed the total fees paid by the Client to the Contractor in the three (3) months preceding the claim.",
        },
        {
            id: 5,
            title: "Arbitration Seat in Singapore",
            type: "Dispute Resolution",
            riskScore: 65,
            riskLevel: "Medium",
            agent: "Risk Scoring",
            negotiable: true,
            confidence: 89,
            original: "Any disputes shall be resolved by arbitration in Singapore under SIAC rules.",
            plain: "If there's a serious disagreement, you have to fly to Singapore to fight it out in arbitration, which is extremely expensive.",
            counter: "Any disputes arising out of this agreement shall be resolved by arbitration in Mumbai, India, in accordance with the Arbitration & Conciliation Act, 1996.",
            financialExposure: "Legal travel costs",
        },
        {
            id: 6,
            title: "60-Day Payment Term",
            type: "Payment",
            riskScore: 72,
            riskLevel: "Medium",
            agent: "Risk Scoring",
            negotiable: true,
            confidence: 95,
            original: "Invoices shall be paid within sixty (60) days of receipt.",
            plain: "You won't see your money until 2 months after you send the invoice.",
            counter: "Invoices shall be paid within fifteen (15) days of receipt.",
        },
        {
            id: 7,
            title: "Confidentiality Definition",
            type: "Confidentiality",
            riskScore: 25,
            riskLevel: "Low",
            agent: "Risk Scoring",
            negotiable: false,
            confidence: 97,
            original: "Confidential info includes all data disclosed during the term.",
            plain: "Standard rule: don't share their private secrets.",
        },
    ],
    agentOutputs: {
        completeness: {
            score: 82,
            status: "Incomplete",
            missing: ["Schedule A — Scope of Work", "Schedule B — Payment Milestones"],
            present: ["Main Agreement", "Definitions", "Signature Page", "Governing Law"],
        },
        risk: {
            score: 7.8,
            critical: 1,
            high: 3,
            medium: 2,
            low: 1,
            topRisk: "Unilateral Termination Without Cause",
        },
        negotiation: {
            counterTermsGenerated: 6,
            strategy: "Lead with S.27 ICA voidability of non-compete, then link IP rights to payment receipt.",
            mostLeverageClause: "Non-Compete (void under Indian law)",
        },
        consistency: {
            contradictions: 2,
            issues: [
                "Payment terms: Clause 4.2 (30 days) vs Clause 9.7 (60 days)",
                "Termination notice: Clause 6.1 (14 days) vs Clause 11.3 (immediate)",
            ],
        },
        regulatory: {
            complianceScore: 68,
            violations: [
                "Non-compete (Cl.3) likely void under Indian Contract Act S.27",
                "No data protection clause per DPDP Act 2023",
                "Liability cap (Cl.4) may be unconscionable under S.23 ICA",
            ],
            jurisdiction: "India — Central / Maharashtra",
        },
        explanation: {
            readabilityScore: 22,
            grade: "Extremely Dense",
            summary:
                "This contract heavily favours the client. Critical issues: unilateral termination with zero payment protection, immediate IP assignment before payment, and a 2-year non-compete that is almost certainly unenforceable under Indian law. Do not sign without negotiating clauses 1, 2, and 3 at minimum.",
        },
    },
};
